### ISSUE TITLE
Proposal for handling an object as first argument of Style.it

### ISSUE THREAD

**Issue by Skywalker13** [buildbreakdo/style-it#24]
Hello, thanks for your lib..

An idea...
Instead of writing this code:
```js
  render() {
    return Style.it(`
      .intro {
        font-size: 40px;
      }
    `,
      <p className="intro">CSS-in-JS made simple -- just Style It.</p>
    );
  }
```

It should be possible to write something like that:
```js
  render() {
    const myCSS = {
      '.intro': {
        fontSize: '40px'
      }
    };

    return Style.it(myCSS, <p className="intro">CSS-in-JS made simple -- just Style It.</p>);
  }
```

And in this case, `Style.it()` will convert the `myCSS` object to the string. It should be easy to implement.

**Comment by buildbreakdo** [comment]
@Skywalker13 Hello! Thanks for opening this issue. What is the use case for the object literal syntax over writing plaintext CSS? Justification for extra characters `'':` (N CSS Properties * `'',`) and `camelCase`?

Object literal syntax can never be feature complete without special syntax hacks because of CSS _value_ prefixes like:

```
cursor: -webkit-grab;
cursor: -moz-grab;
cursor: grab;
display: -webkit-box; 
display: -moz-box;
display: -ms-flexbox;
display: -webkit-flex; 
display: flex;
```

These cannot be declared in a uniform pattern, meaning special corner cases and rules. Things to remember and learn that are not rewarding over the long term.

**Comment by Skywalker13** [comment]
Hi,

The use case is to replace inline Radium styles (bad support for hover, ..., IMHO too slow) by CSS class which are more efficient.
I think that I finally found the project which fits better to my needs: https://github.com/cssinjs/react-jss

feel free to close this issue...

**Comment by buildbreakdo** [comment]
@Skywalker13 Yes, cannot justify adding a hack to fix a bad hack (Radium). Thanks for the dialogue and happy you found something to suit your needs. If you find that it actually doesn't there is a repo which aggregates CSS-in-JS projects that is worth a look: https://github.com/MicheleBertoli/css-in-js

Sounds like you are particularly interested in libraries with the ✓ in "Styles As Object Literals". Best of luck. Cheers.

**Comment by Skywalker13** [comment]
Very interesting repo, thank you
